/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_levex_games_fallingsand_Start */

#ifndef _Included_org_levex_games_fallingsand_Start
#define _Included_org_levex_games_fallingsand_Start
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_levex_games_fallingsand_Start
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_levex_games_fallingsand_Start_getVersion
  (JNIEnv *, jclass);
  
JNIEXPORT jstring JNICALL Java_org_levex_games_fallingsand_Start_getWindowName
  (JNIEnv *, jclass);
  
JNIEXPORT void JNICALL Java_org_levex_games_fallingsand_Start_initNatives
  (JNIEnv *, jclass, jint);
  
JNIEXPORT jstring JNICALL Java_org_levex_games_fallingsand_Start_getNameOfSand
  (JNIEnv *, jclass, jint);


#ifdef __cplusplus
}
#endif
#endif
